// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC10ZR-k-SA72kHUlAD1NqFtYZWdGLEsd8',
    appId: '1:587410682952:web:7456d9f01dcb171a0e547d',
    messagingSenderId: '587410682952',
    projectId: 'cmu-sbnu-vms',
    authDomain: 'cmu-sbnu-vms.firebaseapp.com',
    storageBucket: 'cmu-sbnu-vms.firebasestorage.app',
    measurementId: 'G-MMEKPRK4GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmD-3PxlPWdsPSugK6yNS-TXQ37cBhT5A',
    appId: '1:587410682952:android:d7626add9e63de3c0e547d',
    messagingSenderId: '587410682952',
    projectId: 'cmu-sbnu-vms',
    storageBucket: 'cmu-sbnu-vms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpKiHCcf8ixASbQPu6XxxJiGCn70mtefk',
    appId: '1:587410682952:ios:e5221359f8727f8a0e547d',
    messagingSenderId: '587410682952',
    projectId: 'cmu-sbnu-vms',
    storageBucket: 'cmu-sbnu-vms.firebasestorage.app',
    iosBundleId: 'com.example.cmuSbnuVms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpKiHCcf8ixASbQPu6XxxJiGCn70mtefk',
    appId: '1:587410682952:ios:e5221359f8727f8a0e547d',
    messagingSenderId: '587410682952',
    projectId: 'cmu-sbnu-vms',
    storageBucket: 'cmu-sbnu-vms.firebasestorage.app',
    iosBundleId: 'com.example.cmuSbnuVms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC10ZR-k-SA72kHUlAD1NqFtYZWdGLEsd8',
    appId: '1:587410682952:web:ee100438bb0caf1b0e547d',
    messagingSenderId: '587410682952',
    projectId: 'cmu-sbnu-vms',
    authDomain: 'cmu-sbnu-vms.firebaseapp.com',
    storageBucket: 'cmu-sbnu-vms.firebasestorage.app',
    measurementId: 'G-RE66FCN8ST',
  );
}
